Awesome-Technologies/synapse-admin

src/synapse/dataProvider.js
In the recent Synapse versions at least there's no `next_token` element in the returned JSON for the last batch so to make pagination work I propose using the `from` value in this case. Also actually use the `deactivated` switch value in the requests.
=> Fix pagination and use deactivated users switch

src/components/LoginPage.js
Allow to use homeserver URL with port (e.g. ':443').
=> Allow port in homeserver URL

src/components/users.js
Users are not sortable by `user_id`.
Set `sortable={false}`.
=> Bugfix sort users by `user_id`

src/components/users.js
If you click on a connection in UserEdit, you will get an empty page.
This solves the problem.
=> Bugfix removes the ability to click on individual connections.

src/components/rooms.js, src/i18n/de.js, src/i18n/en.js, src/synapse/dataProvider.js
Add further attributes:
- is_encrypted
- federatable
- public
- state_events
- version
- joined_local_members
Also add the ability to sort.
API was added by synapse v1.13.0.
Fixes: #10
=> Extend the room list with further attributes

src/synapse/dataProvider.js
Information comes natively from the API.
For devices is it part of Synapse 1.23.0
=> Update `total` in dataProvider

src/App.js, src/components/users.js, src/synapse/dataProvider.js
The admin API for user's room memberships is new in synapse v1.21.0.
=> Add a new tab to user page with room memberships

src/App.js, src/components/statistics.js, src/i18n/de.js, src/i18n/en.js, src/synapse/dataProvider.js
The api is new in Synapse 1.23.0.
The list is sortable and filterable.
It is a new list and not part of users' list because you have the chance to filter by date/time.
At the moment the date/time filter is missing in this PR. It needs a datetime picker with result in timestamp.
=> Add new list with information about users' media

src/components/rooms.js, src/i18n/de.js, src/i18n/en.js
Add attribut of rooms `joined_local_devices` to detail view of rooms.
New in Synapse 1.25.0
Fixes #92
=> Add `joined_local_devices` to rooms

package.json, src/App.js, src/components/RoomDirectory.js, src/components/rooms.js, src/components/users.js, src/i18n/de.js, src/i18n/en.js, src/synapse/dataProvider.js
`/_matrix/client/r0/publicRooms`
Related: #100
Missing feature: pagination and filter
The feature can be improved in the future
Pagiation is not easy because of special token for next and previous results.
IMO the dataprovider must be extended to store the token for pagination e.g. in local store, memory, URL or somewhere else.
https://matrix.org/docs/spec/client_server/latest#get-matrix-client-r0-publicrooms
`next_batch` and `prev_batch`
Upgrade to react-admin 3.12.2 is necessary. Because of an fixed bug
`Fix <DeleteWithConfirmButton> does not allow to override resource`
https://github.com/marmelab/react-admin/releases/tag/v3.12.2
=> Add the lists of public rooms on the server

src/synapse/dataProvider.js
Fixes: #149 
The old API is deprecated in Synapse 1.34.0 (2021-05-17).
=> Change delete room API to `DELETE`

.github/workflows/node.js.yml, README.md
This action builds and packages everything into a static site that
can be deployed on any webserver at runtime.
It automatically runs on every pushed tag, ie every release
=> Add github action that packages a release tarball

src/components/RoomDirectory.js, src/components/rooms.js, src/components/users.js
This will be removed in version 4 of react admin.
Upgrade notes:
https://github.com/marmelab/react-admin/blob/next/UPGRADE.md#removed-the-undoable-prop-in-favor-of-mutationmode
Docs:
https://marmelab.com/react-admin/CreateEdit.html#mutationmode
=> replace `undoable` prop with `mutationMode` prop

Dockerfile
Node 17 current fails due to https://github.com/webpack/webpack/issues/14532. It probably makes sense to use the current LTS version of Node instead of the absolute latest version of Node so these kinds of bleeding edge issues are less likely to happen.
=> Switch Dockerfile to use current LTS version of Node

src/components/media.js
```
Material-UI: The `fade` color utility was renamed to `alpha` to better describe its functionality.
You should use `import { alpha } from '@material-ui/core/styles'`
```
For example: https://github.com/marmelab/react-admin/blob/5650aa677e8ccf256822a5bbe76c2a26ad74cd31/packages/ra-ui-materialui/src/button/BulkDeleteWithConfirmButton.tsx#L22-L36
Doc: https://mui.com/guides/migration-v4/#styles
=> Replace deprecated `fade` in `media.js`

src/components/devices.js
```
Material-UI: The `fade` color utility was renamed to `alpha` to better describe its functionality.
You should use `import { alpha } from '@material-ui/core/styles'`
```
For example: https://github.com/marmelab/react-admin/blob/5650aa677e8ccf256822a5bbe76c2a26ad74cd31/packages/ra-ui-materialui/src/button/BulkDeleteWithConfirmButton.tsx#L22-L36
Doc: https://mui.com/guides/migration-v4/#styles
=> Replace deprecated `fade` in `devices.js`

src/components/users.js
Disable not needed ordering in SimpleFormIterator
New feature in [react-admin 3.18.0](https://github.com/marmelab/react-admin/releases/tag/v3.18.0)
> `<SimpleFormIterator>`: Add support for reordering items
PR: https://github.com/marmelab/react-admin/pull/6433
=> `disableReordering` in users' `SimpleFormIterator`

src/components/rooms.js
The `path` is missing at the moment.
=> Add `path` to "members" tab in `ShowRooms`

Dockerfile, README.md
Closes #265 (see for more details and use-case)
This PR adds the two build variables `PUBLIC_URL` and `REACT_APP_SERVER` as argument to the docker build process.
While `PUBLIC_URL` has the default value of `/` if not set, `REACT_APP_SERVER` won't be used at all if not set.
=> Adjusted Dockerfile to include args in build process

.github/workflows/build-test.yml, .github/workflows/edge_ghpage.yml, .github/workflows/github-release.yml
Life cycle / eol of NodeJS: https://endoflife.date/nodejs
=> Bump GHA to NodeJS v16

package.json, yarn.lock
Fixes #277
"improves compatibility with React 18"
```
yarn add --exact react-scripts@^5.0.1
yarn add eslint-config-react-app@^7.0.1 -D
```
See: https://github.com/facebook/create-react-app/blob/main/CHANGELOG.md
=> Bump `react-scripts` to `^5.0.1`

README.md, src/components/users.js, src/i18n/de.js, src/i18n/en.js, src/synapse/dataProvider.js
new in Synapse v1.46.0
To reset a user to a "normal" user `user_type` must be `null`.
https://matrix-org.github.io/synapse/latest/admin_api/user_admin_api.html#create-or-modify-account
=> Add edit `user_type` to user

src/components/users.js
- Move actions for users to the top.
- Show send notice button only if user is activated.
The idea:
- The same design as for the rooms. For the rooms, the actions are also at the top.
- Separate "normale" edit / save button for user from general actions
- Space for further actions, eg.
- [Quarantining all media of a user](https://matrix-org.github.io/synapse/latest/admin_api/media_admin_api.html#quarantining-all-media-of-a-user)
- [Delete media uploaded by a user](https://matrix-org.github.io/synapse/latest/admin_api/media_admin_api.html#delete-media-uploaded-by-a-user)
=> Create `UserEditActions` on user page

src/components/users.js, src/i18n/de.js, src/i18n/en.js
One of my users forgot their password and asked me to change it, which resulted in me unknowingly wiping all of their sessions as a result (due to lack of backup the E2EE keys were also lost). Had I been warned about it before I would've seeked another solution, hence I'm proposing this PR.
Reference: https://matrix-org.github.io/synapse/develop/admin_api/user_admin_api.html#create-or-modify-account
> `password` - string, optional. If provided, the user's password is updated and all devices are logged out.
I'm not sure how translations should be handled - I'm not fluent in the other two languages and didn't want to add a machine generated translation.
=> Add session logout warning below password input

README.md
PUBLIC_URL must not be enclosed in quotation marks, see Awesome-Technologies/synapse-admin#286
- add a note on this in the example
- fix the example itself
fixes Awesome-Technologies/synapse-admin#286
=> doc README: fix PUBLIC_URL in docker-compose example

.travis.yml
Try to fix failure in #297 and #299
Default seems to be `"dist": "xenial"`, https://app.travis-ci.com/github/Awesome-Technologies/synapse-admin/jobs/590193485/config and https://docs.travis-ci.com/user/reference/linux/#overview
See discussion: https://travis-ci.community/t/the-command-npm-config-set-spin-false-failed-and-exited-with-1-during/12909/
=> Set `dist` for Travis CI

src/components/devices.js
`useMutation` have been removed in React Admin v4.
`useDelete` is also valid in React Admin 3.
https://github.com/marmelab/react-admin/blob/next/UPGRADE.md#usequery-usemutation-and-usequerywithstore-have-been-removed
=> Migrate `useMutation` to `useDelete` in `devices.js`

src/components/LoginPage.js
In the PR merged today (#374) I forgot to insert the entry for the Italian language in the login page so that it was visible for the selection.
This mainly because the page on startup takes the local of the machine and during the tests I found it already in Italian.
My bad.
=> Fixed language displayed in login page

.github/workflows/build-test.yml, .github/workflows/edge_ghpage.yml, .github/workflows/github-release.yml, .travis.yml
Life cycle / eol of NodeJS v16 (11 Sep 2023): https://endoflife.date/nodejs
=> Bump NodeJS to v18

public/robots.txt
For an admin GUI it makes no sense to invite crawlers.
It has no additional functional value.
=> disallow crawling in robots.txt

src/components/EventReports.jsx, src/i18n/de.js, src/i18n/en.js
This pull request adds an action to delete event reports. (API: https://matrix-org.github.io/synapse/develop/admin_api/event_reports.html#delete-a-specific-event-report)
It also changes the german translation of the tab name, to something that I think is more fitting. (Can be removed if wished.)
Closes #444 
Note about translations: Since I added a new action, I also had to add some new keys. I only speak English and German, so I wasn't able to translate it to the other languages. I don't know if I have to add these keys anyway to the other languages, and if yes, what I should insert there instead.
=> Allow deletion of event reports

src/components/rooms.jsx, src/components/users.jsx
Disable `bulkActionButtons` for objects where no action is defined or or the meaning is misleading.
For example, in the room list of users. Deleting does not kick the user from the room, but deletes the entire room.
affected:
- user
- connections / sessions (no action implemented)
- joined_rooms (misleading)
- pushers (no action implemented)
- rooms
- members (misleading)
- forward_extremities (no action implemented)
=> Disable bulkActionButtons for not needed room and user tabs

src/components/RegistrationTokens.jsx
=> Update RegistrationTokens.jsx: Fix resource name

Dockerfile
For tools like renovate or dependabot, they like to put changelog notes in PRs updating deps. Having the labels allows the tools to link it back to sourcecode and share commits/release notes
If you want, I can update your github actions to use docker/metadata-action like i did for https://github.com/plankanban/planka/pull/680/files
=> Add source urls to docker so tools can find sourcecode

.dockerignore, Dockerfile, README.md, docker-compose.yml
=> Fix container and path issues

vite.config.ts
Bring back, that the index.html load asstes with relative paths that using in root path ist not required.
`src=/assets/` -> `src=./assets/`
Fixes:
- #517
- #519
Related to:
- #11 
- https://github.com/Awesome-Technologies/synapse-admin/commit/1002b6464a1093b000ebf1d3e9b26cb04526ff11
=> use relative paths for assets to run not in docroot

src/resources/destinations.tsx, src/resources/rooms.tsx, src/resources/users.tsx
Fix several cases of `record` being undefined during the initial render. Happens if a user/room/federation details are open and the user presses F5, doesn't happen during normal navigation.
=> Fix a few undefined records

src/resources/users.tsx
Related / adapted from:
- https://github.com/etkecc/synapse-admin/pull/8
> fixes an annoying problem that when you click on a User form the List, the first (Default) tab doesn't show any data
- https://github.com/etkecc/synapse-admin/pull/16
> fix the user's default tab after creating a new user
> 
> Steps to reproduce:
> 
> 1. Open Users list, click on Create button (/#/users/create)
> 2. Enter user details and click on Save button
> 3. Observe broken default user tab with url encoded hash (/#/users/%40localpart%3Aexample.com), page reload does not help
> 4. Click on the User tab name, and observe working default user tab with not url encoded hash (/#/users/@localpart:example.com)
>
> So, it looks like the problem is with url-encoded hash params
=> fix: show user default tab and after creation

.github/workflows/edge_ghpage.yml
Potential fix for [https://github.com/Awesome-Technologies/synapse-admin/security/code-scanning/7](https://github.com/Awesome-Technologies/synapse-admin/security/code-scanning/7)
To fix the issue, we will add a `permissions` block at the root of the workflow file to explicitly define the minimal permissions required. Based on the actions used in the workflow:
- `actions/checkout` and `actions/setup-node` require `contents: read` to access the repository code.
- `JamesIves/github-pages-deploy-action` requires `pages: write` to deploy the built files to GitHub Pages.
The `permissions` block will be added at the root level to apply to all jobs in the workflow.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
=> Add permissions to ghpages workflow

src/synapse/authProvider.test.ts, src/synapse/authProvider.ts
It is a duplicate to #497
I needed it, that is why this PR without conflicts.
> Since Matrix spec v1, the username when login with password should be sent in the `identifier` field, as explained here: https://spec.matrix.org/v1.1/client-server-api/#matrix-user-id
>
>A full example of a password based login payload can be found here: https://spec.matrix.org/v1.1/client-server-api/#password-based
=> Add identifier when login with password

src/components/ImportFeature.tsx
The current implementation to detect missingFields (header columns) in CSV files is not working as expected and returns wrong results.
This leads to errors as reported in https://github.com/Awesome-Technologies/synapse-admin/issues/600, https://github.com/Awesome-Technologies/synapse-admin/issues/552, https://github.com/Awesome-Technologies/synapse-admin/issues/188.
=> Fixed detecting missingFields in verifyCsv function of CSV import.

src/resources/destinations.tsx
This PR hides zero last retry timestamps that are displayed as 1970/01/01 00:00:00 (misleading) and also improves the dark theme. Without this patch the white rows also have white text in them so the text is invisible unless you point at them, pink rows also have white text that's hard to read, and the reconnect button's color is too bright.
=> Federation page improvements
