src/components/ServerNotices.js, src/components/users.js, src/synapse/dataProvider.js
This adds the button to send "Server Notices" to many users at once.
Replaces PR: #37
=> Add ServerNoticeButton to UserBulkActionButtons

src/components/users.js, src/i18n/de.js, src/i18n/en.js, src/synapse/dataProvider.js
Add information about the user to UserEdit
- creation timestamp
- consent version
=> Add creation timestamp and consent version to UserEdit

src/components/users.js, src/i18n/de.js, src/i18n/en.js
Separates information into individual tabs for a better overview.
=> Move threepids in UserEdit to a separate tab

src/synapse/dataProvider.js
Fixes #70
Bugfix delete a room in room list with `deleteMany`.
=> Bugfix delete room

src/components/ImportFeature.js, src/components/users.js
Fixes #81 
And fix/switch the link to example CSV from absolute URL to a relative URL `./data/example.csv`
=> Bugfix import csv

src/components/rooms.js, src/synapse/dataProvider.js
Replaces #46
Add input field to search in room name.
=> Add SearchInput to RoomFilter

src/i18n/de.js, src/i18n/en.js
Fixes #94 
It has changed since Synapse 1.18.0
=> Update helper text for activate an user

README.md, src/App.js, src/components/EventReports.js, src/i18n/de.js, src/i18n/en.js, src/synapse/dataProvider.js
Fixes #68 
Requires Synapse 1.23.0
Add list and detail view of repoted events
Uses https://github.com/matrix-org/synapse/blob/develop/docs/admin_api/event_reports.rst
=> Add view of reported events

src/components/rooms.js
=> Add delete button to room detail page

README.md, src/App.js, src/components/users.js, src/i18n/de.js, src/i18n/en.js, src/synapse/dataProvider.js
The admin API for user's pushers is new in synapse v1.23.0.
=> Add a new tab to user page with pushers

src/App.js, src/components/users.js, src/i18n/de.js, src/i18n/en.js, src/synapse/dataProvider.js
The admin API for user's media is new in synapse v1.23.0.
=> Add a new tab to user page with media

src/App.js
Disable telemetry which was introduced with react-admin v3.11.0
https://github.com/marmelab/react-admin/releases/tag/v3.11.0
=> Disable telemetry which was introduced with react-admin v3.11.0

src/synapse/authProvider.js
Fixes https://github.com/Awesome-Technologies/synapse-admin/issues/112
=> Name device used by Synapse Admin and hook up logout button

src/synapse/authProvider.js
=> Fix broken redirect to login page

src/components/media.js, src/components/statistics.js, src/i18n/de.js, src/i18n/en.js, src/synapse/dataProvider.js
=> Add button to delete media by size and date

README.md, src/App.js, src/components/rooms.js, src/i18n/de.js, src/i18n/en.js, src/synapse/dataProvider.js
Add a new tab to rooms with state events
The admin API is new in Synapse v1.27.0.
Related: #100
=> Add a new tab to rooms with state events

README.md, src/components/users.js, src/synapse/dataProvider.js
=> Enable sorting in tab of users' media

src/components/LoginPage.js
In my opinion you should know the format of your Homeserver url.
For my Homeserver i need the url format of https://something.xyz/matrix
would fix #134
=> rm url sanity check , maybe fix #134

README.md, src/components/users.js
New in Synapse 1.32.0
Fixes: #132, #136
=> Enable sorting of user list

.env, README.md, src/components/LoginPage.js, src/synapse/authProvider.js
Fixes: #114
Add parameter  `REACT_APP_SERVER` to fix homeserver at build-time.
=> Allow fixed homeserver

src/i18n/en.js
Suggested a UI name change for media size (assuming length is size in bytes)
=> Fix typo on en.js

src/components/RoomDirectory.js
Bug was introduced in https://github.com/Awesome-Technologies/synapse-admin/commit/5ee5288edf7017d6914ea64201bc60b75f9de9a6
=> Fix broken RoomDirectoryFilter

src/components/users.js
=> Fix CSV import button

.github/workflows/build-test.yml
This can be parallel to Travis CI or replace in the future
=> Add GitHub Action to run CI tests

README.md, src/components/users.js, src/i18n/de.js, src/i18n/en.js
=> Add SSO `external_ids` to user

README.md, src/components/users.js
=> Enable modify user `external_ids`

src/components/users.js, src/i18n/de.js, src/i18n/en.js, src/synapse/dataProvider.js
Fixes: #163
and enhance form validation
=> Automatically set the homeserver for a new user

src/components/ServerNotices.js, src/components/users.js
Documentation: https://github.com/marmelab/react-admin/blob/master/docs/CreateEdit.md#toolbar
=> Add `pristine` to `UserEdit` and `ServerNotice`

src/components/RoomDirectory.js
=> Make items in "Room directory" are clickable

README.md, src/components/users.js
=> Add sorting users by creation timestamp

.github/workflows/docker-release.yml
=> version tag on docker hub

.github/workflows/edge_ghpage.yml
Thanks for the nice admin ui.
I just thought about deploying the latest version to GitHub Pages since that makes the application easier to test/use by admins.
Therefore, you might think about merging this PR.
You can see the actual result on the [GH Page of my Fork](https://dfuchss.github.io/synapse-admin)
=> GitHub Pages Deploy

src/components/LoginPage.js, src/i18n/de.js, src/i18n/en.js, src/i18n/zh.js, src/synapse/authProvider.js
Sorry for the latency. Finally it comes back now. Thanks for your patiences and sorry for the inconveniences I've caused.
Optimized a little (since last commit using force refresh to prevent further requests, now using `replaceState` to optimize the performance.) after I've gained more React develop experiences.
Demo site:  https://msa.nya.one
Relates to #124 
Resolve #56
=> feat: support SSO login

README.md
Add some notes to GH pages.
Feel free to modify wording.
https://github.com/Awesome-Technologies/synapse-admin/pull/189#issuecomment-1044594308
=> Add note to GH pages

.github/dependabot.yml
- to keep repo up2date
- to have more transparency what dependabot is doing
current requested PRs by dependabot
```
+------------------------------------------------------------------------+
|                  Changes to Dependabot Pull Requests                   |
+---------+--------------------------------------------------------------+
| created | docker/build-push-action ( from 2 to 3 )                     |
| created | docker/setup-buildx-action ( from 1 to 2 )                   |
| created | JamesIves/github-pages-deploy-action ( from 4.1.5 to 4.4.0 ) |
+---------+--------------------------------------------------------------+
+------------------------------------------------------------+
|            Changes to Dependabot Pull Requests             | …
```
=> Add `dependabot.yml` config

README.md, src/synapse/dataProvider.js
=> Use delete room API v2 (delete room in background)

docker-compose.yml, src/i18n/de.js
Replaces:
- #312 
- #313 
Follow up:
- ee8050f697c9e52283605bafa4eb878daaa82668
- #212
=> Fix broken CI / lint

src/synapse/dataProvider.js
Encode userId to handle the case of a localpart with a forward slash
Fixes: https://github.com/Awesome-Technologies/synapse-admin/issues/258
=> fix: prevent requests from failing

src/components/LoginPage.js, src/components/RoomDirectory.js, src/components/ServerNotices.js, src/components/devices.js, src/components/media.js
The current usage is deprecated and need to be updated:
https://github.com/marmelab/react-admin/pull/6912
=> Update usage of `useNotify` hook

README.md, src/App.js, src/components/destinations.js, src/i18n/de.js, src/i18n/en.js, src/synapse/dataProvider.js
New in Synapse 1.49.0
Docs: https://matrix-org.github.io/synapse/develop/usage/administration/admin_api/federation.html
=> Add admin API for destinations

src/components/RoomDirectory.js, src/components/ServerNotices.js, src/components/devices.js, src/components/media.js, src/components/rooms.js, src/components/users.js
Codestyle only.
See https://marmelab.com/blog/2021/04/07/react-admin-april-update.html#code-classlanguage-textuserecordcontextcode
=> Replace `({ record })` with `useRecordContext()`

package.json, src/App.js, src/components/LoginPage.js, src/i18n/en.js, src/i18n/fr.js, yarn.lock
=> feat: add french translations

.github/workflows/docker-release.yml, .github/workflows/test-docker-image.yml, package.json, src/App.js, src/i18n/it.js, yarn.lock
As the title explains I created an Italian translation for synapse-admin.
I've already tested everything on my machine and it seems to work, but I invite you to do the necessary tests on your machines.
=> Italian translations

package.json, src/components/LoginPage.jsx, src/i18n/fa.js, yarn.lock
Add new PR for Persian language
step1: add fa.js to "/src/i18n/"
step2: add package  "ra-language-farsi"  to package.json
step3: add li to "LoginPage.jsx" line 294 for select Persian langiage
=> Add farsi translations

package.json, src/App.tsx, src/i18n/en.ts, src/i18n/ru.ts, yarn.lock
And thank you for this great tool!
=> Add Russian language support
